#!/usr/bin/env ruby

require 'upwords'

game = Upwords::Game.new(display_on=false)
 
game.add_player("Max")
game.add_player("Jordan")
game.all_refill_racks

Upwords::UI::new(game, row_height=1, col_width=4)

# Upwords::Game.new.run
